-- Grannpojkarna: redigera öppna jobb, säkra kontaktprofiler och direktmeddelanden.
-- Kör efter supabase-migration-7.sql.

create or replace function public.edit_my_open_job(
  p_job_id bigint,
  p_title text,
  p_description text,
  p_location text,
  p_timing text,
  p_budget_sek integer,
  p_price_type text,
  p_category text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if char_length(trim(coalesce(p_title, ''))) not between 4 and 100
    or char_length(trim(coalesce(p_description, ''))) not between 10 and 2000
    or char_length(trim(coalesce(p_location, ''))) not between 2 and 120
    or char_length(trim(coalesce(p_timing, ''))) not between 2 and 80
    or p_budget_sek is null or p_budget_sek not between 1 and 10000000
    or p_price_type not in ('fixed', 'hourly', 'quote')
    or p_category not in (
      'Flytt & bärhjälp', 'Trädgård', 'Montering & småfix', 'Målning',
      'Rengöring', 'Bortforsling & transport', 'Djurpassning',
      'Teknikhjälp', 'Större projekt', 'Övrigt'
    )
  then
    raise exception 'Invalid job data';
  end if;

  update public.jobs
  set
    title = trim(p_title),
    description = trim(p_description),
    location = trim(p_location),
    timing = trim(p_timing),
    budget_sek = p_budget_sek,
    price_type = p_price_type,
    category = p_category
  where id = p_job_id
    and user_id = auth.uid()
    and status = 'open';

  if not found then
    raise exception 'Only your own open jobs can be edited';
  end if;

  return true;
end;
$$;

revoke all on function public.edit_my_open_job(bigint, text, text, text, text, integer, text, text) from public;
grant execute on function public.edit_my_open_job(bigint, text, text, text, text, integer, text, text) to authenticated;

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now(),
  check (sender_id <> recipient_id)
);

create index if not exists direct_messages_participants_created_idx
  on public.direct_messages (sender_id, recipient_id, created_at asc);

create index if not exists direct_messages_recipient_created_idx
  on public.direct_messages (recipient_id, created_at desc);

alter table public.direct_messages enable row level security;

drop policy if exists "Participants can read direct messages" on public.direct_messages;
create policy "Participants can read direct messages"
on public.direct_messages for select
to authenticated
using (
  sender_id = (select auth.uid())
  or recipient_id = (select auth.uid())
);

revoke all on public.direct_messages from anon, authenticated;
grant select on public.direct_messages to authenticated;

create or replace function public.send_direct_message(
  p_recipient_id uuid,
  p_body text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_message_id bigint;
begin
  if auth.uid() is null
    or p_recipient_id is null
    or p_recipient_id = auth.uid()
    or char_length(trim(coalesce(p_body, ''))) not between 1 and 2000
  then
    raise exception 'Invalid direct message';
  end if;

  -- En ny kontakt får bara startas med en utförare. Därefter kan båda svara.
  if not exists (
    select 1
    from public.profiles p
    where p.id = p_recipient_id and p.performer_enabled = true
  ) and not exists (
    select 1
    from public.direct_messages dm
    where (dm.sender_id = auth.uid() and dm.recipient_id = p_recipient_id)
       or (dm.sender_id = p_recipient_id and dm.recipient_id = auth.uid())
  ) then
    raise exception 'A conversation cannot be started with this profile';
  end if;

  insert into public.direct_messages (sender_id, recipient_id, body)
  values (auth.uid(), p_recipient_id, trim(p_body))
  returning id into v_message_id;

  return v_message_id;
end;
$$;

revoke all on function public.send_direct_message(uuid, text) from public;
grant execute on function public.send_direct_message(uuid, text) to authenticated;

create or replace function public.get_contact_profile(p_profile_id uuid)
returns table (
  id uuid,
  display_name text,
  bio text,
  service_area text,
  skills text[],
  avatar_path text,
  performer_enabled boolean,
  availability_status text,
  available_until timestamptz,
  average_rating numeric,
  review_count bigint,
  completed_jobs bigint
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    p.id,
    p.display_name,
    p.bio,
    p.service_area,
    p.skills,
    p.avatar_path,
    p.performer_enabled,
    p.availability_status,
    p.available_until,
    coalesce(r.average_rating, 0),
    coalesce(r.review_count, 0),
    coalesce(j.completed_jobs, 0)
  from public.profiles p
  left join lateral (
    select round(avg(rv.rating)::numeric, 2) as average_rating, count(*) as review_count
    from public.reviews rv
    where rv.reviewee_id = p.id
  ) r on true
  left join lateral (
    select count(*) as completed_jobs
    from public.jobs completed_job
    where completed_job.performer_id = p.id and completed_job.status = 'completed'
  ) j on true
  where p.id = p_profile_id
    and (
      p.performer_enabled = true
      or (
        auth.uid() is not null
        and (
          p.id = auth.uid()
          or exists (
            select 1
            from public.direct_messages dm
            where (dm.sender_id = auth.uid() and dm.recipient_id = p.id)
               or (dm.sender_id = p.id and dm.recipient_id = auth.uid())
          )
          or exists (
            select 1
            from public.jobs participant_job
            where participant_job.status in ('accepted', 'in_progress', 'completed')
              and (
                (participant_job.user_id = auth.uid() and participant_job.performer_id = p.id)
                or (participant_job.performer_id = auth.uid() and participant_job.user_id = p.id)
              )
          )
        )
      )
    );
$$;

revoke all on function public.get_contact_profile(uuid) from public;
grant execute on function public.get_contact_profile(uuid) to anon, authenticated;

alter table public.notifications
  add column if not exists related_user_id uuid references auth.users(id) on delete set null;

alter table public.notifications drop constraint if exists notifications_type_check;
alter table public.notifications
  add constraint notifications_type_check
  check (type in (
    'job_match',
    'application_sent',
    'job_application',
    'job_accepted',
    'application_declined',
    'job_started',
    'job_completed',
    'payout_ready',
    'new_message',
    'direct_message'
  ));

create or replace function public.notify_new_direct_message()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_sender_name text;
begin
  select coalesce(p.display_name, 'En användare')
  into v_sender_name
  from public.profiles p
  where p.id = new.sender_id;

  insert into public.notifications (user_id, type, title, body, related_user_id)
  values (
    new.recipient_id,
    'direct_message',
    'Nytt direktmeddelande',
    coalesce(v_sender_name, 'En användare') || ' har skickat ett meddelande till dig.',
    new.sender_id
  );

  return new;
end;
$$;

drop trigger if exists direct_messages_notify_insert on public.direct_messages;
create trigger direct_messages_notify_insert
after insert on public.direct_messages
for each row execute function public.notify_new_direct_message();

-- Ett timpris är inte ett slutbelopp. Därför skapas ingen utbetalningsnotis
-- för timjobb innan registrerade timmar finns i en senare betalningsversion.
create or replace function public.notify_job_status_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := auth.uid();
  v_amount integer;
begin
  if old.status is not distinct from new.status then
    return new;
  end if;

  if new.status = 'in_progress' then
    if new.user_id is distinct from v_actor_id then
      insert into public.notifications (user_id, type, title, body, job_id)
      values (new.user_id, 'job_started', 'Jobbet har startat', '"' || coalesce(new.title, 'Jobbet') || '" är nu markerat som pågående.', new.id);
    end if;
    if new.performer_id is not null and new.performer_id is distinct from v_actor_id then
      insert into public.notifications (user_id, type, title, body, job_id)
      values (new.performer_id, 'job_started', 'Jobbet har startat', '"' || coalesce(new.title, 'Jobbet') || '" är nu markerat som pågående.', new.id);
    end if;
  elsif new.status = 'completed' and new.performer_id is not null then
    insert into public.notifications (user_id, type, title, body, job_id)
    values (
      new.performer_id,
      'job_completed',
      'Jobbet är slutfört',
      'Beställaren har bekräftat att "' || coalesce(new.title, 'jobbet') || '" är klart.',
      new.id
    );

    if new.price_type <> 'hourly' then
      v_amount := coalesce(new.agreed_price_sek, new.budget_sek, 0);
      insert into public.notifications (user_id, type, title, body, job_id)
      values (
        new.performer_id,
        'payout_ready',
        'Ersättning klar för utbetalning',
        v_amount::text || ' kr för "' || coalesce(new.title, 'jobbet') || '" är markerat som klart för utbetalning.',
        new.id
      );
    end if;
  end if;

  return new;
end;
$$;
