-- Grannpojkarna: kontoanknutet notiscenter.
-- Kör efter supabase-migration-5.sql.

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('job_application', 'job_accepted', 'job_started', 'payout_ready', 'new_message')),
  title text not null check (char_length(title) between 1 and 120),
  body text not null default '' check (char_length(body) <= 500),
  job_id bigint references public.jobs(id) on delete cascade,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_created_idx
  on public.notifications (user_id, created_at desc);

create index if not exists notifications_user_unread_idx
  on public.notifications (user_id, created_at desc)
  where read_at is null;

alter table public.notifications enable row level security;

drop policy if exists "Users can read own notifications" on public.notifications;
create policy "Users can read own notifications"
on public.notifications for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Users can mark own notifications as read" on public.notifications;
create policy "Users can mark own notifications as read"
on public.notifications for update
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

revoke all on public.notifications from anon, authenticated;
grant select on public.notifications to authenticated;
grant update (read_at) on public.notifications to authenticated;

create or replace function public.notify_new_job_application()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_owner_id uuid;
  v_job_title text;
  v_performer_name text;
begin
  select j.user_id, j.title
  into v_owner_id, v_job_title
  from public.jobs j
  where j.id = new.job_id;

  select coalesce(p.display_name, 'En utförare')
  into v_performer_name
  from public.profiles p
  where p.id = new.performer_id;

  if v_owner_id is not null and v_owner_id <> new.performer_id then
    insert into public.notifications (user_id, type, title, body, job_id)
    values (
      v_owner_id,
      'job_application',
      'Ny intresseanmälan',
      coalesce(v_performer_name, 'En utförare') || ' är intresserad av "' || coalesce(v_job_title, 'ditt jobb') || '".',
      new.job_id
    );
  end if;

  return new;
end;
$$;

drop trigger if exists job_applications_notify_insert on public.job_applications;
create trigger job_applications_notify_insert
after insert on public.job_applications
for each row execute function public.notify_new_job_application();

create or replace function public.notify_application_accepted()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_job_title text;
begin
  if old.status is distinct from new.status and new.status = 'accepted' then
    select j.title into v_job_title
    from public.jobs j
    where j.id = new.job_id;

    insert into public.notifications (user_id, type, title, body, job_id)
    values (
      new.performer_id,
      'job_accepted',
      'Du har blivit vald',
      'Beställaren har valt dig för "' || coalesce(v_job_title, 'jobbet') || '". Öppna jobbet för att planera vidare.',
      new.job_id
    );
  end if;

  return new;
end;
$$;

drop trigger if exists job_applications_notify_accept on public.job_applications;
create trigger job_applications_notify_accept
after update of status on public.job_applications
for each row execute function public.notify_application_accepted();

create or replace function public.notify_job_status_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := auth.uid();
  v_amount integer;
begin
  if old.status is not distinct from new.status then
    return new;
  end if;

  if new.status = 'in_progress' then
    if new.user_id is distinct from v_actor_id then
      insert into public.notifications (user_id, type, title, body, job_id)
      values (new.user_id, 'job_started', 'Jobbet har startat', '"' || coalesce(new.title, 'Jobbet') || '" är nu markerat som pågående.', new.id);
    end if;
    if new.performer_id is not null and new.performer_id is distinct from v_actor_id then
      insert into public.notifications (user_id, type, title, body, job_id)
      values (new.performer_id, 'job_started', 'Jobbet har startat', '"' || coalesce(new.title, 'Jobbet') || '" är nu markerat som pågående.', new.id);
    end if;
  elsif new.status = 'completed' and new.performer_id is not null then
    v_amount := coalesce(new.agreed_price_sek, new.budget_sek, 0);
    insert into public.notifications (user_id, type, title, body, job_id)
    values (
      new.performer_id,
      'payout_ready',
      'Jobbet är godkänt',
      v_amount::text || ' kr för "' || coalesce(new.title, 'jobbet') || '" är markerat som klart för utbetalning.',
      new.id
    );
  end if;

  return new;
end;
$$;

drop trigger if exists jobs_notify_status_change on public.jobs;
create trigger jobs_notify_status_change
after update of status on public.jobs
for each row execute function public.notify_job_status_change();

create or replace function public.notify_new_job_message()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_recipient_id uuid;
  v_job_title text;
begin
  select
    case when j.user_id = new.sender_id then j.performer_id else j.user_id end,
    j.title
  into v_recipient_id, v_job_title
  from public.jobs j
  where j.id = new.job_id;

  if v_recipient_id is not null and v_recipient_id <> new.sender_id then
    insert into public.notifications (user_id, type, title, body, job_id)
    values (
      v_recipient_id,
      'new_message',
      'Nytt meddelande',
      'Du har fått ett nytt meddelande om "' || coalesce(v_job_title, 'jobbet') || '".',
      new.job_id
    );
  end if;

  return new;
end;
$$;

drop trigger if exists job_messages_notify_insert on public.job_messages;
create trigger job_messages_notify_insert
after insert on public.job_messages
for each row execute function public.notify_new_job_message();

