-- Grannpojkarna: frivillig profilbild/presentation, matchning, betyg och intjänat.
-- Kör efter supabase-migration-2.sql.

alter table public.profiles
  add column if not exists avatar_path text,
  add column if not exists savings_goal_sek integer;

alter table public.profiles drop constraint if exists profiles_savings_goal_check;
alter table public.profiles
  add constraint profiles_savings_goal_check
  check (savings_goal_sek is null or savings_goal_sek between 1 and 100000000);

alter table public.jobs
  add column if not exists performer_id uuid references auth.users(id) on delete set null,
  add column if not exists agreed_price_sek integer,
  add column if not exists completed_at timestamptz;

alter table public.jobs drop constraint if exists jobs_agreed_price_check;
alter table public.jobs
  add constraint jobs_agreed_price_check
  check (agreed_price_sek is null or agreed_price_sek between 1 and 10000000);

create index if not exists jobs_performer_status_idx
  on public.jobs (performer_id, status, completed_at desc);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  job_id bigint not null unique references public.jobs(id) on delete cascade,
  reviewer_id uuid not null references auth.users(id) on delete cascade,
  reviewee_id uuid not null references auth.users(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  comment text check (comment is null or char_length(comment) between 2 and 600),
  created_at timestamptz not null default now()
);

create index if not exists reviews_reviewee_id_idx
  on public.reviews (reviewee_id, created_at desc);

alter table public.reviews enable row level security;

drop policy if exists "Users can read relevant reviews" on public.reviews;
create policy "Users can read relevant reviews"
on public.reviews for select
to authenticated
using (
  reviewer_id = (select auth.uid())
  or reviewee_id = (select auth.uid())
);

drop policy if exists "Job owners can review performers" on public.reviews;
create policy "Job owners can review performers"
on public.reviews for insert
to authenticated
with check (
  reviewer_id = (select auth.uid())
  and reviewer_id <> reviewee_id
  and exists (
    select 1
    from public.jobs
    where jobs.id = job_id
      and jobs.user_id = (select auth.uid())
      and jobs.performer_id = reviewee_id
      and jobs.status = 'completed'
  )
);

drop policy if exists "Performers can read assigned jobs" on public.jobs;
create policy "Performers can read assigned jobs"
on public.jobs for select
to authenticated
using ((select auth.uid()) = performer_id);

grant select, insert on public.reviews to authenticated;
grant usage, select on sequence public.reviews_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'profile-images',
  'profile-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public profile images are readable" on storage.objects;
create policy "Public profile images are readable"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'profile-images');

drop policy if exists "Users can upload own profile image" on storage.objects;
create policy "Users can upload own profile image"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'profile-images'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "Users can update own profile image" on storage.objects;
create policy "Users can update own profile image"
on storage.objects for update
to authenticated
using (
  bucket_id = 'profile-images'
  and (storage.foldername(name))[1] = (select auth.uid())::text
)
with check (
  bucket_id = 'profile-images'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "Users can delete own profile image" on storage.objects;
create policy "Users can delete own profile image"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'profile-images'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create or replace function public.get_job_applications(p_job_id bigint)
returns table (
  application_id bigint,
  performer_id uuid,
  message text,
  proposed_price_sek integer,
  status text,
  created_at timestamptz,
  display_name text,
  bio text,
  service_area text,
  skills text[],
  avatar_path text,
  average_rating numeric,
  review_count bigint
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.jobs
    where id = p_job_id and user_id = auth.uid()
  ) then
    return;
  end if;

  return query
  select
    ja.id,
    ja.performer_id,
    ja.message,
    ja.proposed_price_sek,
    ja.status,
    ja.created_at,
    p.display_name,
    p.bio,
    p.service_area,
    p.skills,
    p.avatar_path,
    coalesce(round(avg(r.rating)::numeric, 2), 0),
    count(r.id)
  from public.job_applications ja
  join public.profiles p on p.id = ja.performer_id
  left join public.reviews r on r.reviewee_id = ja.performer_id
  where ja.job_id = p_job_id
  group by ja.id, p.id
  order by
    case ja.status when 'accepted' then 0 when 'pending' then 1 else 2 end,
    ja.created_at asc;
end;
$$;

create or replace function public.accept_job_application(
  p_application_id bigint,
  p_agreed_price_sek integer
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_job_id bigint;
  v_performer_id uuid;
begin
  if p_agreed_price_sek is null or p_agreed_price_sek < 1 or p_agreed_price_sek > 10000000 then
    raise exception 'Invalid agreed price';
  end if;

  select ja.job_id, ja.performer_id
  into v_job_id, v_performer_id
  from public.job_applications ja
  join public.jobs j on j.id = ja.job_id
  where ja.id = p_application_id
    and ja.status = 'pending'
    and j.status = 'open'
    and j.user_id = auth.uid();

  if v_job_id is null then
    raise exception 'Application not available';
  end if;

  update public.job_applications
  set status = case when id = p_application_id then 'accepted' else 'declined' end
  where job_id = v_job_id and status = 'pending';

  update public.jobs
  set status = 'matched', performer_id = v_performer_id, agreed_price_sek = p_agreed_price_sek
  where id = v_job_id and user_id = auth.uid();

  return true;
end;
$$;

create or replace function public.complete_job(p_job_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.jobs
  set status = 'completed', completed_at = now()
  where id = p_job_id
    and user_id = auth.uid()
    and performer_id is not null
    and status = 'matched';

  if not found then
    raise exception 'Job cannot be completed';
  end if;

  return true;
end;
$$;

revoke all on function public.get_job_applications(bigint) from public;
revoke all on function public.accept_job_application(bigint, integer) from public;
revoke all on function public.complete_job(bigint) from public;

grant execute on function public.get_job_applications(bigint) to authenticated;
grant execute on function public.accept_job_application(bigint, integer) to authenticated;
grant execute on function public.complete_job(bigint) to authenticated;
