-- Grannpojkarna: beställare/utförare, publik jobblista och uppringningsförfrågningar.
-- Skriptet är avsett att köras en gång efter den första supabase-setup.sql.

alter table public.profiles
  add column if not exists account_type text not null default 'private',
  add column if not exists performer_enabled boolean not null default false,
  add column if not exists service_area text,
  add column if not exists skills text[] not null default '{}',
  add column if not exists bio text;

update public.profiles
set account_type = 'company'
where role = 'company';

update public.profiles
set performer_enabled = true
where role in ('helper', 'company');

alter table public.profiles drop constraint if exists profiles_account_type_check;
alter table public.profiles
  add constraint profiles_account_type_check check (account_type in ('private', 'company'));

alter table public.jobs
  add column if not exists title text,
  add column if not exists price_type text not null default 'fixed';

update public.jobs
set title = left(description, 100)
where title is null;

alter table public.jobs alter column title set not null;
alter table public.jobs drop constraint if exists jobs_title_check;
alter table public.jobs
  add constraint jobs_title_check check (char_length(title) between 4 and 100);

alter table public.jobs drop constraint if exists jobs_price_type_check;
alter table public.jobs
  add constraint jobs_price_type_check check (price_type in ('fixed', 'hourly', 'quote'));

alter table public.jobs drop constraint if exists jobs_category_check;
alter table public.jobs
  add constraint jobs_category_check check (category in (
    'Flytt & bärhjälp',
    'Trädgård',
    'Montering & småfix',
    'Målning',
    'Rengöring',
    'Bortforsling & transport',
    'Djurpassning',
    'Teknikhjälp',
    'Större projekt',
    'Övrigt'
  ));

create table if not exists public.job_applications (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  performer_id uuid not null references auth.users(id) on delete cascade,
  message text not null check (char_length(message) between 10 and 1000),
  proposed_price_sek integer check (proposed_price_sek between 1 and 10000000),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'withdrawn')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (job_id, performer_id)
);

create table if not exists public.callback_requests (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 100),
  phone text not null check (char_length(phone) between 7 and 30),
  preferred_time text not null check (char_length(preferred_time) between 2 and 80),
  description text not null check (char_length(description) between 5 and 1000),
  consent boolean not null check (consent = true),
  status text not null default 'new' check (status in ('new', 'contacted', 'published', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists jobs_status_created_at_idx
  on public.jobs (status, created_at desc);
create index if not exists jobs_category_idx
  on public.jobs (category);
create index if not exists job_applications_job_id_idx
  on public.job_applications (job_id);
create index if not exists job_applications_performer_id_idx
  on public.job_applications (performer_id);
create index if not exists callback_requests_status_created_at_idx
  on public.callback_requests (status, created_at desc);

alter table public.job_applications enable row level security;
alter table public.callback_requests enable row level security;

drop policy if exists "Anyone can read open jobs" on public.jobs;
create policy "Anyone can read open jobs"
on public.jobs for select
to anon, authenticated
using (status = 'open');

drop policy if exists "Users can read own jobs" on public.jobs;
create policy "Users can read own jobs"
on public.jobs for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Performers can create applications" on public.job_applications;
create policy "Performers can create applications"
on public.job_applications for insert
to authenticated
with check (
  performer_id = (select auth.uid())
  and exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.performer_enabled = true
  )
  and exists (
    select 1 from public.jobs
    where jobs.id = job_id
      and jobs.status = 'open'
      and jobs.user_id <> (select auth.uid())
  )
);

drop policy if exists "Users can read relevant applications" on public.job_applications;
create policy "Users can read relevant applications"
on public.job_applications for select
to authenticated
using (
  performer_id = (select auth.uid())
  or exists (
    select 1 from public.jobs
    where jobs.id = job_id
      and jobs.user_id = (select auth.uid())
  )
);

drop policy if exists "Job owners can update applications" on public.job_applications;
create policy "Job owners can update applications"
on public.job_applications for update
to authenticated
using (
  exists (
    select 1 from public.jobs
    where jobs.id = job_id
      and jobs.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.jobs
    where jobs.id = job_id
      and jobs.user_id = (select auth.uid())
  )
);

drop policy if exists "Performers can withdraw applications" on public.job_applications;
create policy "Performers can withdraw applications"
on public.job_applications for delete
to authenticated
using (performer_id = (select auth.uid()) and status = 'pending');

drop policy if exists "Anyone can request a callback" on public.callback_requests;
create policy "Anyone can request a callback"
on public.callback_requests for insert
to anon, authenticated
with check (
  consent = true
  and char_length(name) between 2 and 100
  and char_length(phone) between 7 and 30
  and char_length(description) between 5 and 1000
);

grant select on public.jobs to anon, authenticated;
grant insert, select, delete on public.job_applications to authenticated;
grant update (status) on public.job_applications to authenticated;
grant insert on public.callback_requests to anon, authenticated;

grant usage, select on sequence public.job_applications_id_seq to authenticated;
grant usage, select on sequence public.callback_requests_id_seq to anon, authenticated;

drop trigger if exists job_applications_set_updated_at on public.job_applications;
create trigger job_applications_set_updated_at
before update on public.job_applications
for each row execute function public.set_updated_at();

drop trigger if exists callback_requests_set_updated_at on public.callback_requests;
create trigger callback_requests_set_updated_at
before update on public.callback_requests
for each row execute function public.set_updated_at();
