-- Grannpojkarna: accepterade/pågående jobb och privat jobbchatt.
-- Kör efter supabase-migration-3.sql. Migration 4 behövs för tillgänglighetsfunktionen.

alter table public.jobs
  add column if not exists accepted_at timestamptz,
  add column if not exists started_at timestamptz;

alter table public.jobs drop constraint if exists jobs_status_check;

update public.jobs
set
  status = 'accepted',
  accepted_at = coalesce(accepted_at, updated_at, now())
where status = 'matched';

alter table public.jobs
  add constraint jobs_status_check
  check (status in ('open', 'accepted', 'in_progress', 'completed', 'cancelled'));

create index if not exists jobs_participant_status_idx
  on public.jobs (user_id, performer_id, status, updated_at desc);

-- Statusbyten görs bara via funktionerna nedan så att flödet inte kan hoppas över.
revoke update on public.jobs from authenticated;
drop policy if exists "Users can update own jobs" on public.jobs;

create table if not exists public.job_messages (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists job_messages_job_created_idx
  on public.job_messages (job_id, created_at asc);

alter table public.job_messages enable row level security;

drop policy if exists "Users can delete own jobs" on public.jobs;
create policy "Users can delete own jobs"
on public.jobs for delete
to authenticated
using (
  (select auth.uid()) = user_id
  and status in ('open', 'cancelled')
);

drop policy if exists "Job participants can read messages" on public.job_messages;
create policy "Job participants can read messages"
on public.job_messages for select
to authenticated
using (
  exists (
    select 1
    from public.jobs
    where jobs.id = job_messages.job_id
      and (
        jobs.user_id = (select auth.uid())
        or jobs.performer_id = (select auth.uid())
      )
      and jobs.status in ('accepted', 'in_progress', 'completed')
  )
);

drop policy if exists "Job participants can send messages" on public.job_messages;
create policy "Job participants can send messages"
on public.job_messages for insert
to authenticated
with check (
  sender_id = (select auth.uid())
  and exists (
    select 1
    from public.jobs
    where jobs.id = job_messages.job_id
      and (
        jobs.user_id = (select auth.uid())
        or jobs.performer_id = (select auth.uid())
      )
      and jobs.status in ('accepted', 'in_progress')
  )
);

grant select, insert on public.job_messages to authenticated;
grant usage, select on sequence public.job_messages_id_seq to authenticated;

create or replace function public.accept_job_application(
  p_application_id bigint,
  p_agreed_price_sek integer
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_job_id bigint;
  v_performer_id uuid;
begin
  if p_agreed_price_sek is null or p_agreed_price_sek < 1 or p_agreed_price_sek > 10000000 then
    raise exception 'Invalid agreed price';
  end if;

  select ja.job_id, ja.performer_id
  into v_job_id, v_performer_id
  from public.job_applications ja
  join public.jobs j on j.id = ja.job_id
  where ja.id = p_application_id
    and ja.status = 'pending'
    and j.status = 'open'
    and j.user_id = auth.uid();

  if v_job_id is null then
    raise exception 'Application not available';
  end if;

  update public.job_applications
  set status = case when id = p_application_id then 'accepted' else 'declined' end
  where job_id = v_job_id and status = 'pending';

  update public.jobs
  set
    status = 'accepted',
    performer_id = v_performer_id,
    agreed_price_sek = p_agreed_price_sek,
    accepted_at = now(),
    started_at = null,
    completed_at = null
  where id = v_job_id and user_id = auth.uid();

  return true;
end;
$$;

create or replace function public.start_job(p_job_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.jobs
  set status = 'in_progress', started_at = now()
  where id = p_job_id
    and status = 'accepted'
    and performer_id is not null
    and (
      user_id = auth.uid()
      or performer_id = auth.uid()
    );

  if not found then
    raise exception 'Job cannot be started';
  end if;

  return true;
end;
$$;

create or replace function public.complete_job(p_job_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.jobs
  set status = 'completed', completed_at = now()
  where id = p_job_id
    and user_id = auth.uid()
    and performer_id is not null
    and status = 'in_progress';

  if not found then
    raise exception 'Job cannot be completed';
  end if;

  return true;
end;
$$;

revoke all on function public.accept_job_application(bigint, integer) from public;
revoke all on function public.start_job(bigint) from public;
revoke all on function public.complete_job(bigint) from public;

grant execute on function public.accept_job_application(bigint, integer) to authenticated;
grant execute on function public.start_job(bigint) to authenticated;
grant execute on function public.complete_job(bigint) to authenticated;
